baseurl = "https://www.example.com"
title = "Calaix desastre"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true
copyright = "© 2019 Marc Riera"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  # titleEmoji = ":tada:"
  twitter = "mrcasals"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "post series"
  url = "series/"


[[params.menu]]
  name = "about"
  url = "about/"


[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true