backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: "assets/images"
site_url: https://mrcasals.me
slug:
  encoding: "ascii"
  clean_accents: true
collections:
  - name: "posts"
    label: "Post"
    folder: "_posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Títol", name: "title", widget: "string" }
      - {
          label: "Publicat?",
          name: "published",
          widget: "boolean",
          default: false,
        }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Etiquetes", name: "tags", widget: "list" }
      - { label: "Cos", name: "body", widget: "markdown" }
  - name: "languages"
    label: "Petit Príncep - Idioma"
    folder: "_petit_princep_languages"
    create: true
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Nom en català", name: "title", widget: "string" }
      - { label: "Parlants", name: "speakers", widget: "string" }
      - { label: "Autònim", name: "autonym", widget: "string" }
      - {
          label: "Transcripció IPA",
          name: "ipa_transcription",
          widget: "string",
        }
      - { label: "Països", name: "countries", widget: "string" }
      - {
          label: "Sistema d'escriptura",
          name: "writing_system",
          widget: "string",
        }

  - name: "books"
    label: "Petit Príncep - Llibre"
    folder: "_petit_princep_books"
    create: true
    slug: "{{fleds.slug}}"
    editor:
      preview: false
    fields:
      - { label: "Títol", name: "title", widget: "string", required: false }
      - {
          label: "Transliteració a l'alfabet llatí",
          name: "transliteration",
          widget: "string",
          required: false,
        }
      - {
          label: "Nota sobre el títol",
          name: "note_on_title",
          widget: "string",
          required: false,
        }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - { label: "Idioma", name: "language", widget: "string", required: false }
      - { label: "ISBN", name: "isbn", widget: "string", required: false }
      - {
          label: "Any d'edició",
          name: "year",
          widget: "string",
          required: false,
        }
      - {
          label: "Editorial",
          name: "publisher",
          widget: "string",
          required: false,
        }
      - {
          label: "Traductor",
          name: "translator",
          widget: "string",
          required: false,
        }
      - {
          label: "Comprat a",
          name: "bought",
          widget: "string",
          required: false,
        }
      - {
          label: "Portat per",
          name: "brought_by",
          widget: "string",
          required: false,
        }
      - {
          label: "Número de la col·lecció",
          name: "number",
          widget: "string",
          required: false,
        }
      - {
          label: "Descripció",
          name: "body",
          widget: "markdown",
          required: false,
        }
